---
abstract: 'Proxy a directory of HTML::Formhandler forms'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Catalyst::Test: '0'
  HTML::Formhandler: '0'
  HTTP::Request::Common: '0'
  Test::Most: '0.34'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.032, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-Model-HTMLFormhandler
requires:
  Catalyst: '5.90060'
  Module::Pluggable: '5.1'
  Moose: '2.1403'
  Scalar::Util: '0'
resources:
  bugtracker: https://github.com/jjn1056/Catalyst-Model-HTMLFormhandler/issues
  homepage: https://github.com/jjn1056/Catalyst-Model-HTMLFormhandler
  repository: https://github.com/jjn1056/Catalyst-Model-HTMLFormhandler.git
version: '0.004'
